name:shell commands

on:[push,pull]

jobs:
  run shell commands
   runs-on:ubuntu-latest
   steps:
      name:string
      run: echo "Welcome to my sample workflow"
      name:multiline script
      run:|
        node -v
        npm -v
